export type ObjectStatus =
  | "certified"
  | "provisional"
  | "diagnostic"
  | "stale"
  | "empirically held";

export type MapObject = {
  id: string;
  kind: "node" | "packet";
  area: string;
  eyebrow: string;
  title: string;
  status: ObjectStatus;
  meaning: string;
  equation: string;
  sources: string[];
  inputs: string[];
  outputs: string[];
  caveats: string[];
  command: string;
  x?: number;
  y?: number;
};

export type MapEdge = {
  id: string;
  from: string;
  to: string;
  label: string;
  bend?: number;
};

export type Trace = {
  id: string;
  label: string;
  shortLabel: string;
  description: string;
  question: string;
  nodes: string[];
  edges: string[];
  packets: string[];
};

export const STATUS_COPY: Record<ObjectStatus, string> = {
  certified: "Verified implementation or exactly repeated artifact; this does not by itself certify the full calibration.",
  provisional: "Active object whose measurement, estimate, or economic interpretation is not frozen.",
  diagnostic: "Useful for mechanism or sensitivity analysis, but not a promoted production result.",
  stale: "Superseded or historical object retained only for comparison.",
  "empirically held": "Blocked from promotion by an unresolved empirical measurement or provenance issue.",
};

export const NODES: MapObject[] = [
  {
    id: "empirical-builders",
    kind: "node",
    area: "Evidence",
    eyebrow: "01 / DATA",
    title: "Empirical builders",
    status: "empirically held",
    meaning: "Reproducible CPS, NCHS, ACS/MMS, and PSID builders turn survey records into moments with explicit samples and estimators.",
    equation: "m̂_k = estimator_k(raw data, sample, weights, fixed effects)",
    sources: [
      "code/data/cps_fertility/build_cps_fertility_targets.py",
      "code/data/nchs_natality_timing/build_first_birth_timing.R",
      "code/data/mms_center_periphery/build_intergen_one_market_housing_targets.R",
      "code/data/psid_followup_mar2026/sa_rooms_first_birth_one_variant_v1.do",
      "code/data/moment_standard_errors/build_moment_bootstrap_se.R",
    ],
    inputs: ["survey microdata", "sample definitions", "weights", "estimators"],
    outputs: ["point estimates", "standard errors", "provenance rows"],
    caveats: ["The PSID rooms builder still needs an authoritative valid-code rule for ACTUALROOMS_ values 0 and 99."],
    command: "python code/data/cps_fertility/build_cps_fertility_targets.py",
    x: 8,
    y: 22,
  },
  {
    id: "provenance-ledger",
    kind: "node",
    area: "Evidence",
    eyebrow: "02 / LEDGER",
    title: "Target provenance",
    status: "empirically held",
    meaning: "The ledger states what each model statistic means, which empirical object it matches, and why a row is clean, provisional, or blocked.",
    equation: "target row = (builder, estimator, sample, FE, cluster, value, uncertainty)",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/e5_profile.py",
      "code/model/intergen_eqscale_seq_optimized/calibration.py",
      "code/data/moment_standard_errors/SPEC_moment_bootstrap_se.md",
      "CALIBRATION_STATUS.md",
    ],
    inputs: ["builder artifacts", "measurement definitions", "author decisions"],
    outputs: ["authoritative target rows", "holds", "source caveats"],
    caveats: ["Only the first-birth rooms row has full E5 provenance metadata in e5_profile.py; several rows still rely on comments and the separate specification ledger."],
    command: "rg -n 'E5_TARGET_PROVENANCE|TARGET_MOMENT_OBJECTS' code/model/intergen_eqscale_seq_optimized",
    x: 8,
    y: 60,
  },
  {
    id: "target-contract",
    kind: "node",
    area: "Calibration",
    eyebrow: "03 / CONTRACT",
    title: "E5 target contract",
    status: "empirically held",
    meaning: "A signed target-and-weight system defines the twelve moments the retained E5b parameter vector is judged against.",
    equation: "\u2110_T = {(m̂_k, w_k)}_{k=1}^{12},   w_k = 1 / SE_k²",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/e5_profile.py",
      "code/model/intergen_eqscale_seq_optimized/target_system.py",
      "code/cluster/submit_intergen_e5b_idfe.sh",
    ],
    inputs: ["empirical moments", "uncertainty", "target-set name"],
    outputs: ["fingerprint", "identification gate", "loss rows"],
    caveats: ["The contract is computationally pinned, but the first-birth rooms input is under empirical hold, so the refit cannot be promoted."],
    command: "cd code/model && PYTHONPATH=$PWD .venv/bin/python -m unittest intergen_eqscale_seq_optimized.tests.test_e5_profile",
    x: 24,
    y: 38,
  },
  {
    id: "smm-objective",
    kind: "node",
    area: "Calibration",
    eyebrow: "04 / SMM",
    title: "Objective + search",
    status: "certified",
    meaning: "Each candidate parameter vector solves the equilibrium, measures all model moments, and is ranked by the fingerprinted diagonal SMM loss.",
    equation: "J(θ) = Σ_k w_k [m_k(θ) − m̂_k]²",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/run_e1_chain.py",
      "code/model/intergen_eqscale_seq_optimized/collect_e1.py",
      "code/cluster/submit_intergen_e5b_idfe_collector.sh",
    ],
    inputs: ["candidate θ", "target fingerprint", "solver moments"],
    outputs: ["loss contributions", "checkpoints", "eligible winner"],
    caveats: ["The loss is not a formal J-test because some standard errors are declared or synthetic. The collector must compare against the incumbent, not only new chains."],
    command: "cd code/cluster && E5B_IDFE_MODE=smoke sbatch --array=1-2 submit_intergen_e5b_idfe.sh",
    x: 24,
    y: 78,
  },
  {
    id: "parameters",
    kind: "node",
    area: "Households",
    eyebrow: "05 / PRIMITIVES",
    title: "Parameters + externals",
    status: "provisional",
    meaning: "Ten free coordinates govern patience, child utility, fertility noise, housing demand, supply scale, and bequests; three objects are held externally.",
    equation: "θ ∈ Θ,   minimum owner cash = (1−φ)pH",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/e5_profile.py",
      "code/model/intergen_eqscale_seq_optimized/externals.py",
      "code/model/intergen_eqscale_seq_optimized/parameters.py",
    ],
    inputs: ["search bounds", "external restrictions", "economic units"],
    outputs: ["candidate primitives", "income process", "housing menu"],
    caveats: ["The current estimates inherit the empirical hold. Parameters at or near bounds require economic diagnosis rather than cosmetic reweighting."],
    command: "sed -n '35,120p' code/model/intergen_eqscale_seq_optimized/e5_profile.py",
    x: 40,
    y: 20,
  },
  {
    id: "household-problem",
    kind: "node",
    area: "Households",
    eyebrow: "06 / BELLMAN",
    title: "Lifecycle household",
    status: "certified",
    meaning: "A finite-lived household chooses fertility, tenure and house size, consumption, rental space, and saving under income risk and bequest motives.",
    equation: "W(x)=E_ε max_{o',c,h^R,b'}{u(c,s;m)+ε^H(o')+βs_aE[V(x')]+β(1−s_a)B(w^e)}",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/parameters.py",
      "latex/dynamic_intergenerational_housing_fertility_model.tex",
    ],
    inputs: ["state x", "parameters", "prices", "policy wedges"],
    outputs: ["value functions", "decision rules", "choice probabilities"],
    caveats: ["The retained E5b specification uses a shared child clock. The independent-child maturation repair is an unpromoted alternative requiring re-estimation."],
    command: "PYTHONPATH=code/model code/model/.venv/bin/python -m intergen_eqscale_seq_optimized.run_seq_smoke --cells 0",
    x: 40,
    y: 55,
  },
  {
    id: "fertility-choice",
    kind: "node",
    area: "Households",
    eyebrow: "07 / FERTILITY",
    title: "Birth attempt hazard",
    status: "provisional",
    meaning: "Eligible households choose whether to attempt the next birth; biological fecundity maps attempts into realized births and separate noise scales govern first and later margins.",
    equation: "π^F(x)=exp(V¹/κ(n)) / [exp(V⁰/κ(n))+exp(V¹/κ(n))]",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/e5_profile.py",
      "code/model/intergen_eqscale_seq_optimized/tests/test_eqscale_seq.py",
    ],
    inputs: ["wait value", "attempt value", "fecundity", "parity"],
    outputs: ["birth probabilities", "parity transitions", "birth flows"],
    caveats: ["Fertility is a flow hazard; completed fertility is a stock. The housing response after a second birth is not a second-birth hazard target."],
    command: "cd code/model && PYTHONPATH=$PWD .venv/bin/python -m unittest intergen_eqscale_seq_optimized.tests.test_eqscale_seq",
    x: 40,
    y: 86,
  },
  {
    id: "tenure-savings",
    kind: "node",
    area: "Households",
    eyebrow: "08 / BALANCE SHEET",
    title: "Tenure, savings + bequests",
    status: "certified",
    meaning: "Renters choose continuous rooms; owners select a discrete rung, finance the down payment, save liquid wealth, and value terminal estate wealth.",
    equation: "cash ≥ (1−φ)pH,   B(w^e)=θ₀(θ₁+max{w^e,0})¹⁻σ/(1−σ)",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/parameters.py",
      "code/model/intergen_eqscale_seq_optimized/tests/test_bequest_target_moments.py",
    ],
    inputs: ["liquid wealth", "inherited tenure", "house price", "financed share φ"],
    outputs: ["tenure", "rooms", "b'", "estate wealth"],
    caveats: ["The down-payment threshold uses (1−φ), because φ is the financed share. Conditional renter policies are not realized housing after the tenure choice."],
    command: "cd code/model && PYTHONPATH=$PWD .venv/bin/python -m unittest intergen_eqscale_seq_optimized.tests.test_bequest_target_moments",
    x: 56,
    y: 20,
  },
  {
    id: "kfe",
    kind: "node",
    area: "Aggregation",
    eyebrow: "09 / KFE",
    title: "Stationary distribution",
    status: "certified",
    meaning: "The forward routine pushes entrant mass through savings, tenure, income, fertility, child aging, survival, and lifecycle exit to construct the stationary cross-section.",
    equation: "g' = Τ_{θ,p}(g) + e,   g'=g",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/tests/test_eqscale_seq.py",
      "code/model/tools/check_population_closure.py",
    ],
    inputs: ["policies", "transition matrices", "entrant cohort"],
    outputs: ["g(x)", "moments", "births", "housing quantities"],
    caveats: ["The maintained routine constructs a normalized stationary cross-section. It is not the one-period unnormalized pushforward required for a calendar-time transition."],
    command: "cd code/model && .venv/bin/python tools/check_population_closure.py",
    x: 56,
    y: 58,
  },
  {
    id: "housing-demand",
    kind: "node",
    area: "Markets",
    eyebrow: "10 / QUANTITIES",
    title: "Physical housing demand",
    status: "certified",
    meaning: "The distribution weights realized renter rooms and physical owner rungs; the owner service premium affects utility but not market quantity.",
    equation: "H^D(p,g)=∫ [1_R h^R(x)+1_O H(o'(x))] dg(x)",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/tools/build_intergen_mechanics_packet.py",
    ],
    inputs: ["stationary g", "realized tenure", "renter rooms", "owner rung"],
    outputs: ["demand per adult", "tenure quantities", "market residual"],
    caveats: ["Never substitute conditional renter housing or utility services χH for realized physical housing demand."],
    command: "rg -n 'markov_market_housing_demand|housing_demand' code/model/intergen_eqscale_seq_optimized/solver.py",
    x: 72,
    y: 22,
  },
  {
    id: "price-clearing",
    kind: "node",
    area: "Markets",
    eyebrow: "11 / CLEARING",
    title: "Supply + price loop",
    status: "certified",
    meaning: "A scalar price search repeatedly resolves household policies and the distribution until physical demand equals the upward-sloping supply schedule.",
    equation: "pₜᵃʳᵍᵉᵗ = r̄ [H^D/H₀]^(1/ξ) / user-cost-rate",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/parameters.py",
    ],
    inputs: ["housing demand", "H₀", "supply elasticity", "user cost"],
    outputs: ["asset price p", "rent r", "clearing residual"],
    caveats: ["The current price is a stationary asset price. The generic transition illustration's housing-cost index is a different object."],
    command: "rg -n 'solve_markov_income_equilibrium|refine_one_market_markov_income' code/model/intergen_eqscale_seq_optimized/solver.py",
    x: 72,
    y: 58,
  },
  {
    id: "births-maturation",
    kind: "node",
    area: "Renewal",
    eyebrow: "12 / COHORTS",
    title: "Births + maturation",
    status: "provisional",
    meaning: "Realized births enter the household child state and later generate mature potential entrant households through the maintained shared-clock conversion.",
    equation: "F=∫ f(x)dg(x),   B₀ = mature-child household equivalents",
    sources: [
      "code/model/intergen_eqscale_seq_optimized/solver.py",
      "code/model/intergen_eqscale_seq_optimized/parameters.py",
      "code/model/tools/audit_closed_reproductive_closure.py",
    ],
    inputs: ["birth flows", "child clock", "entrant conversion"],
    outputs: ["dependent children", "mature entrant flow B₀"],
    caveats: ["Changing the child clock changes entrant timing and is quantitatively material; it must be re-estimated before promotion."],
    command: "cd code/model && .venv/bin/python tools/audit_closed_reproductive_closure.py --smoke",
    x: 88,
    y: 22,
  },
  {
    id: "population-closure",
    kind: "node",
    area: "Renewal",
    eyebrow: "13 / SCALE",
    title: "Entrants + population closure",
    status: "diagnostic",
    meaning: "Required young entrants, mature local entrants, outside inflow, and retention jointly determine the stationary adult-household scale.",
    equation: "S E₀(p,g)=M+ρ S B₀(p,g),   S=M/[E₀−ρB₀]",
    sources: [
      "code/model/tools/build_population_closure_update.py",
      "code/model/tools/audit_closed_reproductive_closure.py",
      "output/model/population_closure_update/",
      "CALIBRATION_STATUS.md",
    ],
    inputs: ["E₀", "B₀", "outside flow M", "retention ρ", "price"],
    outputs: ["stationary scale S", "aggregate demand", "total births"],
    caveats: ["This is an open stationary comparison, not a U.S. calendar-time transition. The retained fertility block has no positive closed reproductive root over the audited range."],
    command: "cd code/model && .venv/bin/python tools/build_population_closure_update.py --solve-policies",
    x: 88,
    y: 58,
  },
  {
    id: "policy-engine",
    kind: "node",
    area: "Outputs",
    eyebrow: "14 / POLICY",
    title: "Counterfactual contracts",
    status: "diagnostic",
    meaning: "Policy drivers alter taxes, grants, credit, supply, or retention while holding the approved closure objects fixed and jointly resolving prices, scale, and transfers where required.",
    equation: "policy equilibrium: household optimum + housing clearing + renewal + fiscal balance",
    sources: [
      "code/model/tools/run_e5_repaired_policy_with_entry.py",
      "code/model/tools/run_intergen_funded_policy_with_entry.py",
      "code/model/tools/build_population_closure_update.py",
    ],
    inputs: ["baseline estimate", "policy wedge", "closure contract"],
    outputs: ["Δ fertility", "Δ tenure", "Δ price", "Δ population"],
    caveats: ["No policy result is promoted while the rooms target is under hold. Diagnostic closure values cannot silently become production defaults."],
    command: "cd code/model && .venv/bin/python tools/build_population_closure_update.py --solve-policies",
    x: 88,
    y: 88,
  },
  {
    id: "diagnostics-paper",
    kind: "node",
    area: "Outputs",
    eyebrow: "15 / READOUT",
    title: "Diagnostics + paper",
    status: "provisional",
    meaning: "Stable graph packets expose policies, boundary states, prices, quantities, market residuals, and the paper-facing interpretation.",
    equation: "artifact = render(solution cache, contract metadata, stable figure set)",
    sources: [
      "code/model/tools/build_intergen_mechanics_packet.py",
      "latex/dynamic_intergenerational_housing_fertility_model.tex",
      "output/pdf/dynamic_intergenerational_housing_fertility_model.pdf",
    ],
    inputs: ["solution", "target fit", "policy cases", "status caveats"],
    outputs: ["visual packet", "tables", "paper PDF"],
    caveats: ["The optional calendar-time architecture in the report is a proposal. The maintained quantitative exercise remains stationary."],
    command: "cd code/model && .venv/bin/python tools/build_population_closure_update.py --solve-policies",
    x: 72,
    y: 88,
  },
  {
    id: "spatial-predecessor",
    kind: "node",
    area: "Historical context",
    eyebrow: "ARCHIVE / 2-LOCATION",
    title: "Center–periphery predecessor",
    status: "stale",
    meaning: "The earlier two-location Python model remains valuable for spatial mechanisms and source comparison, but it is not the retained August E5b quantitative path.",
    equation: "H_i^D(p_i,g)=H_{0i}(r_i/r̄_i)^{η_i},   i∈{center,periphery}",
    sources: [
      "code/model/dt_cp_model/solver.py",
      "code/model/dt_cp_model/objective.py",
      "latex/model_writeup.tex",
    ],
    inputs: ["two locations", "amenities", "migration", "local supply"],
    outputs: ["spatial sorting", "location prices", "legacy diagnostics"],
    caveats: ["Do not mix its losses, targets, room normalization, or policy claims with the one-market E5b strand."],
    command: "cd code/model && .venv/bin/python -m dt_cp_model.cli smoke --quiet",
    x: 8,
    y: 89,
  },
];

export const PACKETS: MapObject[] = [
  {
    id: "packet-moments",
    kind: "packet",
    area: "Evidence",
    eyebrow: "PACKET / MOMENTS",
    title: "Empirical moment",
    status: "empirically held",
    meaning: "A target value travels with its estimator, sample, uncertainty, and caveat—never as an unlabelled scalar.",
    equation: "(μ̂_k, SE_k, provenance_k)",
    sources: ["code/model/intergen_eqscale_seq_optimized/e5_profile.py"],
    inputs: ["builder output"],
    outputs: ["target contract row"],
    caveats: ["The first-birth rooms packet is blocked pending valid-code remeasurement."],
    command: "npm run refresh",
  },
  {
    id: "packet-parameters",
    kind: "packet",
    area: "Calibration",
    eyebrow: "PACKET / θ",
    title: "Candidate parameters",
    status: "provisional",
    meaning: "One bounded parameter vector is passed into the exact same solver path used for measurement and policy diagnostics.",
    equation: "θ = (β,Δα,Δα₁,ψ,κ₁,κ_C,χ,H₀,θ₀,θ₁)",
    sources: ["code/model/intergen_eqscale_seq_optimized/e5_profile.py"],
    inputs: ["search proposal"],
    outputs: ["household primitives"],
    caveats: ["Bounds and external restrictions are part of the identifying contract."],
    command: "sed -n '75,115p' code/model/intergen_eqscale_seq_optimized/e5_profile.py",
  },
  {
    id: "packet-policies",
    kind: "packet",
    area: "Households",
    eyebrow: "PACKET / RULES",
    title: "Household policy rules",
    status: "certified",
    meaning: "Value and policy arrays carry savings, renter rooms, tenure, location, and fertility choices into the forward distribution.",
    equation: "σ_θ,p(x) = {b'(x), h^R(x), o'(x), π^F(x)}",
    sources: ["code/model/intergen_eqscale_seq_optimized/solver.py"],
    inputs: ["value functions"],
    outputs: ["KFE transitions"],
    caveats: ["The Bellman-to-KFE fertility probability side channel must correspond to the accepted price evaluation."],
    command: "rg -n '_fert2_probs' code/model/intergen_eqscale_seq_optimized/solver.py",
  },
  {
    id: "packet-distribution",
    kind: "packet",
    area: "Aggregation",
    eyebrow: "PACKET / g",
    title: "Household distribution",
    status: "certified",
    meaning: "Mass over age, wealth, income, tenure, parity, and child state weights every model moment and physical market quantity.",
    equation: "g(x)≥0,   ∫g(x)dx=1",
    sources: ["code/model/intergen_eqscale_seq_optimized/solver.py"],
    inputs: ["entrant mass", "transition kernel"],
    outputs: ["moments", "demand", "births"],
    caveats: ["This packet is normalized composition, not a calendar-time level distribution G_t."],
    command: "rg -n 'forward_distribution_markov_income' code/model/intergen_eqscale_seq_optimized/solver.py",
  },
  {
    id: "packet-demand",
    kind: "packet",
    area: "Markets",
    eyebrow: "PACKET / Hᴰ",
    title: "Housing demand",
    status: "certified",
    meaning: "Expected physical rooms, aggregated over the realized tenure choice, travel to the market-clearing block.",
    equation: "H^D=∫h(x)dg(x)",
    sources: ["code/model/intergen_eqscale_seq_optimized/solver.py"],
    inputs: ["g", "housing rules"],
    outputs: ["excess demand"],
    caveats: ["Owner utility services χH are not physical demand."],
    command: "rg -n 'markov_market_housing_demand' code/model/intergen_eqscale_seq_optimized/solver.py",
  },
  {
    id: "packet-prices",
    kind: "packet",
    area: "Markets",
    eyebrow: "PACKET / p",
    title: "Housing price",
    status: "certified",
    meaning: "The candidate stationary asset price returns to household budgets until the quantity residual meets the solver tolerance.",
    equation: "p ← p + λ(p_target−p)",
    sources: ["code/model/intergen_eqscale_seq_optimized/solver.py"],
    inputs: ["demand", "supply"],
    outputs: ["rent", "down payment", "user cost"],
    caveats: ["Do not identify this stationary asset price with a contemporaneous transition cost index."],
    command: "rg -n 'p_target|scalar_market_refine' code/model/intergen_eqscale_seq_optimized/solver.py",
  },
  {
    id: "packet-births",
    kind: "packet",
    area: "Renewal",
    eyebrow: "PACKET / F",
    title: "Realized births",
    status: "provisional",
    meaning: "Birth flows change current child states and feed the future entrant pipeline.",
    equation: "F=∫f(x)dg(x)",
    sources: ["code/model/intergen_eqscale_seq_optimized/solver.py"],
    inputs: ["fertility hazard", "g"],
    outputs: ["children at home", "future entrants"],
    caveats: ["Birth timing inherits the retained shared-clock architecture."],
    command: "rg -n 'first_births_by_age|total_births_kfe' code/model/intergen_eqscale_seq_optimized/solver.py",
  },
  {
    id: "packet-entrants",
    kind: "packet",
    area: "Renewal",
    eyebrow: "PACKET / B₀",
    title: "Mature entrants",
    status: "diagnostic",
    meaning: "Mature local-born household equivalents combine with outside inflow to cover the young entrants required by the stationary cross-section.",
    equation: "entry pool = M + ρ S B₀",
    sources: ["code/model/tools/audit_closed_reproductive_closure.py"],
    inputs: ["maturation", "retention", "outside inflow"],
    outputs: ["entrant cohort", "scale identity"],
    caveats: ["Outside and local entrants currently share a fixed entrant-state distribution."],
    command: "cd code/model && .venv/bin/python tools/audit_closed_reproductive_closure.py --smoke",
  },
  {
    id: "packet-policy",
    kind: "packet",
    area: "Outputs",
    eyebrow: "PACKET / Δ",
    title: "Policy wedge",
    status: "diagnostic",
    meaning: "A labeled policy change enters budgets or supply together with an explicit fiscal and population-closure contract.",
    equation: "τ, grant, φ, H₀, ρ → new equilibrium",
    sources: ["code/model/tools/build_population_closure_update.py"],
    inputs: ["baseline", "policy definition"],
    outputs: ["counterfactual equilibrium"],
    caveats: ["Policy outputs remain diagnostic while the empirical target hold is open."],
    command: "cd code/model && .venv/bin/python tools/build_population_closure_update.py --solve-policies",
  },
];

export const OBJECTS: Record<string, MapObject> = Object.fromEntries(
  [...NODES, ...PACKETS].map((item) => [item.id, item]),
);

export const EDGES: MapEdge[] = [
  { id: "e-data-ledger", from: "empirical-builders", to: "provenance-ledger", label: "builder artifacts", bend: -34 },
  { id: "e-ledger-contract", from: "provenance-ledger", to: "target-contract", label: "moments + provenance", bend: 18 },
  { id: "e-contract-smm", from: "target-contract", to: "smm-objective", label: "targets + weights", bend: -28 },
  { id: "e-smm-parameters", from: "smm-objective", to: "parameters", label: "candidate θ", bend: -62 },
  { id: "e-parameters-household", from: "parameters", to: "household-problem", label: "primitives", bend: -20 },
  { id: "e-household-fertility", from: "household-problem", to: "fertility-choice", label: "wait / attempt values", bend: -18 },
  { id: "e-household-tenure", from: "household-problem", to: "tenure-savings", label: "budgets + values", bend: 22 },
  { id: "e-fertility-kfe", from: "fertility-choice", to: "kfe", label: "birth transitions", bend: -34 },
  { id: "e-tenure-kfe", from: "tenure-savings", to: "kfe", label: "policy rules", bend: 24 },
  { id: "e-kfe-smm", from: "kfe", to: "smm-objective", label: "model moments", bend: 82 },
  { id: "e-kfe-demand", from: "kfe", to: "housing-demand", label: "g(x)", bend: -28 },
  { id: "e-demand-market", from: "housing-demand", to: "price-clearing", label: "Hᴰ", bend: -20 },
  { id: "e-market-household", from: "price-clearing", to: "household-problem", label: "price p", bend: -78 },
  { id: "e-kfe-births", from: "kfe", to: "births-maturation", label: "birth flow F", bend: -32 },
  { id: "e-births-pop", from: "births-maturation", to: "population-closure", label: "mature B₀", bend: -16 },
  { id: "e-pop-demand", from: "population-closure", to: "housing-demand", label: "scale S", bend: 58 },
  { id: "e-policy-household", from: "policy-engine", to: "household-problem", label: "tax / grant / credit", bend: 92 },
  { id: "e-policy-market", from: "policy-engine", to: "price-clearing", label: "supply + fiscal", bend: -24 },
  { id: "e-market-readout", from: "price-clearing", to: "diagnostics-paper", label: "prices + residuals", bend: 16 },
  { id: "e-pop-readout", from: "population-closure", to: "diagnostics-paper", label: "scale + total births", bend: 28 },
  { id: "e-kfe-readout", from: "kfe", to: "diagnostics-paper", label: "policies + distribution", bend: 54 },
];

export const TRACES: Trace[] = [
  {
    id: "calibration",
    label: "Calibration",
    shortLabel: "CAL",
    description: "Follow one empirical moment into the signed target contract, through a candidate equilibrium, and back as a loss contribution.",
    question: "Which evidence disciplines each free parameter, and where does the current empirical hold break promotion?",
    nodes: ["empirical-builders", "provenance-ledger", "target-contract", "smm-objective", "parameters", "household-problem", "tenure-savings", "fertility-choice", "kfe"],
    edges: ["e-data-ledger", "e-ledger-contract", "e-contract-smm", "e-smm-parameters", "e-parameters-household", "e-household-fertility", "e-household-tenure", "e-fertility-kfe", "e-tenure-kfe", "e-kfe-smm"],
    packets: ["packet-moments", "packet-parameters", "packet-policies", "packet-distribution"],
  },
  {
    id: "housing",
    label: "Housing-market equilibrium",
    shortLabel: "HOU",
    description: "Trace the stationary price through tenure and space choices, the KFE, physical demand, supply, and the scalar price update.",
    question: "Is a surprising price response coming from household demand, distributional mass, supply, or the clearing algorithm?",
    nodes: ["household-problem", "tenure-savings", "kfe", "housing-demand", "price-clearing"],
    edges: ["e-household-tenure", "e-tenure-kfe", "e-kfe-demand", "e-demand-market", "e-market-household"],
    packets: ["packet-prices", "packet-policies", "packet-distribution", "packet-demand"],
  },
  {
    id: "population",
    label: "Intergenerational feedback",
    shortLabel: "POP",
    description: "Follow births into the child clock, mature entrants, stationary scale, aggregate demand, prices, and the next fertility response.",
    question: "Which link is economics and which is accounting: fertility, maturation, retention, outside inflow, scale, or prices?",
    nodes: ["fertility-choice", "kfe", "births-maturation", "population-closure", "housing-demand", "price-clearing", "household-problem"],
    edges: ["e-fertility-kfe", "e-kfe-births", "e-births-pop", "e-pop-demand", "e-demand-market", "e-market-household"],
    packets: ["packet-births", "packet-entrants", "packet-demand", "packet-prices"],
  },
  {
    id: "policy",
    label: "Policy counterfactual",
    shortLabel: "POL",
    description: "Trace a labeled tax, grant, credit, supply, or retention change through household decisions, prices, population scale, fiscal balance, and paper outputs.",
    question: "Does the claimed effect survive the closure contract, fiscal balance, equilibrium price response, and current empirical hold?",
    nodes: ["policy-engine", "household-problem", "tenure-savings", "fertility-choice", "kfe", "housing-demand", "price-clearing", "births-maturation", "population-closure", "diagnostics-paper"],
    edges: ["e-policy-household", "e-policy-market", "e-household-tenure", "e-household-fertility", "e-tenure-kfe", "e-fertility-kfe", "e-kfe-demand", "e-demand-market", "e-kfe-births", "e-births-pop", "e-pop-demand", "e-market-readout", "e-pop-readout", "e-kfe-readout"],
    packets: ["packet-policy", "packet-policies", "packet-distribution", "packet-demand", "packet-prices", "packet-births", "packet-entrants"],
  },
];

export const AREAS = [
  { label: "EVIDENCE", x: 0, width: 16 },
  { label: "CALIBRATION", x: 16, width: 16 },
  { label: "HOUSEHOLDS", x: 32, width: 32 },
  { label: "MARKETS", x: 64, width: 16 },
  { label: "RENEWAL + OUTPUTS", x: 80, width: 20 },
];
