"""Provisional fourteen-moment calibration contract for the July 2026 ledger."""

from __future__ import annotations

from typing import Any

from .m5_profile import M5_THETA, m5_overrides
from .target_system import TargetSystem


NEW_MOMENT_PROFILE_NAME = "intergen_new_moment_ledger_20260722"

# One declared moment per free parameter.  The four ``*_parameter`` rows are
# first-stage auxiliary estimates from the CEX LES exercise; the remaining rows
# are generated by the structural model.
NEW_MOMENT_TARGETS = {
    "aggregate_wealth_to_annual_after_tax_earnings": 6.90,
    "annual_bequest_flow_to_aggregate_wealth": 0.0088,
    "old_total_estate_wealth_to_annual_income_p90_7684": 4.53,
    "alpha_cons_parameter": 0.732605,
    "c_bar_0_parameter": 0.397044,
    "h_bar_0_parameter": 2.629803,
    "c_bar_n_parameter": 0.043655,
    "housing_increment_0to1": 0.664435,
    "prime30_55_parent_3plus_minus_1to2_mean_rooms": 0.367700,
    "tfr": 1.918,
    "childless_rate": 0.188,
    "own_rate": 0.575472,
    "four_year_tenure_residual_variance": 0.117113,
    "aggregate_mean_occupied_rooms_18_85": 5.779970,
}

# Equal squared percentage deviations.  This is deliberately transparent for
# the preliminary three-hour search and avoids mixing units across the new
# auxiliary estimates before a joint covariance matrix is available.
NEW_MOMENT_WEIGHTS = {
    name: 1.0 / (target * target) for name, target in NEW_MOMENT_TARGETS.items()
}

NEW_MOMENT_SEED = {
    **M5_THETA,
    "alpha_cons": NEW_MOMENT_TARGETS["alpha_cons_parameter"],
    "c_bar_0": NEW_MOMENT_TARGETS["c_bar_0_parameter"],
    "h_bar_0": NEW_MOMENT_TARGETS["h_bar_0_parameter"],
    "c_bar_n": NEW_MOMENT_TARGETS["c_bar_n_parameter"],
}


def new_moment_target_system() -> TargetSystem:
    system = TargetSystem.from_mappings(
        "new_moment_ledger_14_v1_relative_loss",
        NEW_MOMENT_TARGETS,
        NEW_MOMENT_WEIGHTS,
    )
    system.require_identified(free_parameter_count=14)
    return system


def new_moment_overrides(*, tight: bool = True, optimized: bool = True) -> dict[str, Any]:
    """Use the current M5 model and numerical contract with the new seed."""

    return {
        **m5_overrides(tight=tight, optimized=optimized),
        **NEW_MOMENT_SEED,
    }
