"""Bridge person-law household heads into the lifecycle distribution.

The first integration closure preserves the model's conditional distribution
of wealth, tenure, income, parity, and children within each age cell while
rescaling that cell to the household-head mass generated by the person law.
Positive rescaling is the provisional state distribution for newly formed or
migrant heads; negative rescaling represents head dissolution or demographic
exit. The mass operation is exact and separately reported so this provisional
composition assumption cannot be mistaken for an estimated formation model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

import numpy as np

from .person_cohort_law import CohortState


Array = np.ndarray


@dataclass(frozen=True)
class HeadMassRebalanceLedger:
    """Age-cell mass changes imposed by the person-to-head bridge."""

    mass_before: Array
    target_mass: Array
    mass_after: Array
    added_mass: Array
    removed_mass: Array
    scale_factors: Array
    maximum_age_mass_residual: float
    total_mass_residual: float


def aggregate_heads_to_model_age_cells(
    state: CohortState,
    *,
    age_start: int,
    cell_width: int,
    number_of_cells: int,
) -> Array:
    """Aggregate sex-specific single-year heads to model age cells."""

    validated = state.validated()
    if age_start < 0 or cell_width < 1 or number_of_cells < 1:
        raise ValueError("Invalid model age-cell definition")
    stop = age_start + cell_width * number_of_cells
    if stop > validated.heads.shape[1]:
        raise ValueError(
            f"Model age cells end at {stop - 1}, beyond person age support "
            f"{validated.heads.shape[1] - 1}"
        )
    return np.asarray(
        [
            float(np.sum(validated.heads[:, lower : lower + cell_width]))
            for lower in range(age_start, stop, cell_width)
        ],
        dtype=float,
    )


def _age_slice(ndim: int, age_axis: int, age: int) -> tuple[object, ...]:
    index: list[object] = [slice(None)] * ndim
    index[age_axis] = int(age)
    return tuple(index)


def rebalance_household_distribution_by_age(
    distribution: Array,
    target_age_mass: Array,
    *,
    age_axis: int = 3,
    empty_age_templates: Mapping[int, Array] | None = None,
    tolerance: float = 1e-12,
) -> tuple[Array, HeadMassRebalanceLedger]:
    """Rescale each age cell to an externally generated head-mass target.

    A positive target for an empty source cell requires a nonnegative template
    whose shape equals that age slice. The template is normalized internally.
    No mass is moved across ages by this function.
    """

    source = np.asarray(distribution, dtype=float)
    if source.ndim < 2:
        raise ValueError("distribution must have at least two dimensions")
    if not np.all(np.isfinite(source)) or np.min(source) < -tolerance:
        raise ValueError("distribution must be finite and nonnegative")
    axis = int(age_axis)
    if axis < 0:
        axis += source.ndim
    if not 0 <= axis < source.ndim:
        raise ValueError("age_axis is outside the distribution dimensions")
    targets = np.asarray(target_age_mass, dtype=float).reshape(-1)
    if targets.shape != (source.shape[axis],):
        raise ValueError(
            f"target_age_mass has shape {targets.shape}; expected {(source.shape[axis],)}"
        )
    if np.any(~np.isfinite(targets)) or np.any(targets < -tolerance):
        raise ValueError("target_age_mass must be finite and nonnegative")
    targets = np.maximum(targets, 0.0)

    output = np.maximum(source, 0.0).copy()
    before = np.zeros_like(targets)
    after = np.zeros_like(targets)
    factors = np.full_like(targets, np.nan)
    templates = {} if empty_age_templates is None else dict(empty_age_templates)
    for age in range(len(targets)):
        index = _age_slice(output.ndim, axis, age)
        cell = output[index]
        mass = float(np.sum(cell))
        target = float(targets[age])
        before[age] = mass
        if target <= tolerance:
            output[index] = 0.0
            factors[age] = 0.0
        elif mass > tolerance:
            factor = target / mass
            output[index] = cell * factor
            factors[age] = factor
        else:
            if age not in templates:
                raise RuntimeError(
                    f"Age cell {age} has zero source mass and positive target {target:.12g}"
                )
            template = np.asarray(templates[age], dtype=float)
            if template.shape != cell.shape:
                raise ValueError(
                    f"Template {age} has shape {template.shape}; expected {cell.shape}"
                )
            if np.any(~np.isfinite(template)) or np.min(template) < -tolerance:
                raise ValueError(f"Template {age} must be finite and nonnegative")
            template_mass = float(np.sum(template))
            if template_mass <= tolerance:
                raise ValueError(f"Template {age} has zero mass")
            output[index] = target * template / template_mass
            factors[age] = np.inf
        after[age] = float(np.sum(output[index]))

    residuals = after - targets
    maximum_residual = float(np.max(np.abs(residuals)))
    total_residual = float(np.sum(output)) - float(np.sum(targets))
    scale = max(1.0, float(np.max(targets)))
    if maximum_residual > tolerance * scale:
        raise RuntimeError(
            f"Age-cell head-mass bridge failed by {maximum_residual:.6g}"
        )
    return output, HeadMassRebalanceLedger(
        mass_before=before,
        target_mass=targets,
        mass_after=after,
        added_mass=np.maximum(targets - before, 0.0),
        removed_mass=np.maximum(before - targets, 0.0),
        scale_factors=factors,
        maximum_age_mass_residual=maximum_residual,
        total_mass_residual=total_residual,
    )
